In [1]:
# Step 1: Import Libraries
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, classification_report, r2_score
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder

# Step 2: Load Dataset from Local File
df = pd.read_csv("/content/iris.csv")   # change if your file name is different

print("Dataset Preview:")
print(df.head())

# Step 3: Convert Categorical Target to Numeric
le = LabelEncoder()
df['species'] = le.fit_transform(df['species'])

# Step 4: Split Features and Target
X = df.drop("species", axis=1)
y = df["species"]

# Step 5: Train Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Step 6: Create KNN Model
knn = KNeighborsClassifier(n_neighbors=5)

# Step 7: Train Model
knn.fit(X_train, y_train)

# Step 8: Make Predictions
y_pred = knn.predict(X_test)

# Step 9: Confusion Matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Step 10: Classification Report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Step 11: R2 Score
print("\nR2 Score:")
print(r2_score(y_test, y_pred))

# Step 12: Cross Validation
scores = cross_val_score(knn, X, y, cv=5)

print("\nCross Validation Scores:", scores)
print("Average Cross Validation Score:", scores.mean())

Dataset Preview:
   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30


R2 Score:
1.0

Cross Validation Scores: [0.96666667 1.         0.93333333 0.96666667 1.        ]
Average Cross Validation Score: 0.973333