In [1]:
import numpy as np

np.random.seed(100)

# 30 students, 5 subjects (marks between 35 and 100)
marks = np.random.randint(35, 101, size=(30, 5))
print("Marks Data:\n", marks)

# 1. Total marks per student
student_total = np.sum(marks, axis=1)
print("\nTotal Marks Per Student:\n", student_total)

# 2. Average marks per student
student_avg = np.mean(marks, axis=1)
print("\nAverage Marks Per Student:\n", student_avg)

# 3. Total marks per subject
subject_total = np.sum(marks, axis=0)
print("\nTotal Marks Per Subject:\n", subject_total)

# 4. Hardest subject (lowest total)
hard_subject = np.argmin(subject_total)
print("\nHardest Subject Index:", hard_subject)

# 5. Topper student
topper = np.argmax(student_total)
print("Topper Student Index:", topper)

# 6. Class average
class_avg = np.mean(student_total)
print("\nClass Average:", class_avg)

# 7. Students below class average
below_avg_students = np.where(student_total < class_avg)
print("\nStudents Below Average:\n", below_avg_students)

# 8. Rank students (lowest to highest)
ranking = np.argsort(student_total)
print("\nStudent Ranking (Low to High):\n", ranking)

# 9. Distinction students (avg >= 75)
distinction = np.where(student_avg >= 75)
print("\nDistinction Students:\n", distinction)

# 10. Normalize marks (0–1 scale)
min_val = marks.min()
max_val = marks.max()
normalized_marks = (marks - min_val) / (max_val - min_val)
print("\nNormalized Marks:\n", normalized_marks)

Marks Data:
 [[ 43  59  83  45  87]
 [ 88  49  69  59  50]
 [ 95  93  51  44  37]
 [ 62  39  66  36  48]
 [ 39  94  42  84  82]
 [100  96  49  90  37]
 [ 54  98  88  62  91]
 [ 65  83  82  74  73]
 [ 79  53  99  91  69]
 [ 88  52  48  65  52]
 [ 88  85  88  35  48]
 [ 92  38  38  45  95]
 [ 38  83  87  78  71]
 [ 40  73  77  68  93]
 [ 77  57  35  90  54]
 [ 88  97  85  70  58]
 [ 44  83  56  60  89]
 [ 41  72  93  74  86]
 [ 65  59  90  52  80]
 [ 80  70  51  47  55]
 [ 45  43  65  47  53]
 [ 79  92  35  89  51]
 [ 40  86  69  89  36]
 [ 49  68  55  75  59]
 [ 93  63  42  37  98]
 [ 37  52  88  65  63]
 [ 72  52  45  48  60]
 [ 50  46  73  57  90]
 [ 92  86  83  88  52]
 [100  77  79  51  86]]

Total Marks Per Student:
 [317 315 320 251 341 372 393 377 391 305 344 308 357 351 313 398 332 366
 346 303 253 346 320 306 333 305 277 316 401 393]

Average Marks Per Student:
 [63.4 63.  64.  50.2 68.2 74.4 78.6 75.4 78.2 61.  68.8 61.6 71.4 70.2
 62.6 79.6 66.4 73.2 69.2 60.6 50.6 69.2 64.  