In [1]:
import numpy as np
array = np.array([2, 4, 6, 8])
print(array)
print(type(array))
print(array * 3)

[2 4 6 8]
<class 'numpy.ndarray'>
[ 6 12 18 24]


In [2]:
import numpy as np

zeros1 = np.zeros(4)
print(zeros1)

zeros = np.zeros((3, 2))
print(zeros)

ones = np.ones((2, 4))
print(ones)

[0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [3]:
import numpy as np

arr = np.array([[2, 4],[6, 8]])
print(arr.size)

arr1 = np.array([[1, 3, 5],
                 [2, 4, 6],
                 [7, 8, 9]])
print(arr1.size)
print(arr1)
print(arr)
print(type(arr))

4
9
[[1 3 5]
 [2 4 6]
 [7 8 9]]
[[2 4]
 [6 8]]
<class 'numpy.ndarray'>


In [4]:
import numpy as np

a = np.arange(2, 10)
print(a)

b = a.reshape(4, 2)
print(b)

[2 3 4 5 6 7 8 9]
[[2 3]
 [4 5]
 [6 7]
 [8 9]]


In [5]:
import numpy as np

arr = np.array([[7,8],[9,10],[11,12]])

print(arr[-1])
print(arr[2][1])

arr1 = np.array([[[2,3],[4,5]],[[6,7],[8,9]]])
print(arr1[1])

[11 12]
12
[[6 7]
 [8 9]]


In [6]:
import numpy as np

a = np.array([2, 4, 6, 8])
b = np.array([1, 2, 3, 4])

print(a / b)
print(a + 5)
print(a * 2)
print(np.sum(a))
print(np.max(a))

[2. 2. 2. 2.]
[ 7  9 11 13]
[ 4  8 12 16]
20
8


In [7]:
import numpy as np

a = np.array([2, 4, 6, 8])
b = np.array([1, 3, 5, 7])

print(np.std(a))
print(np.std(b))

2.23606797749979
2.23606797749979


In [8]:
import numpy as np

a = np.array([[2, 3, 4],
              [5, 6, 7],
              [8, 9, 1]])

print(np.linalg.norm(a))

16.881943016134134


In [9]:
import numpy as np

a = np.array([[2, 1],
              [4, 3]])

b = np.array([[1, 0],
              [2, 1]])

print(a @ b)

[[ 4  1]
 [10  3]]


In [10]:
import numpy as np

arr = np.array([[2, 4, 6],
                [1, 3, 5]])

b = np.array([5, 10, 15])

print(arr + b)

[[ 7 14 21]
 [ 6 13 20]]


In [11]:
import numpy as np

a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

print(np.dot(a, b))

44


In [12]:
import numpy as np

arr = np.array([[2, 4, 6],
                [8, 10, 12]])

print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))

[10 14 18]
[12 30]


In [13]:
import numpy as np

a = np.array([[2, 4],
              [6, 8],
              [10, 12]])

print(a.T)

[[ 2  6 10]
 [ 4  8 12]]


In [14]:
import numpy as np

a = np.array([2, 4, 6, 8])
b = np.array([1, 3, 5, 7])

print(np.mean(a))
print(np.mean(b))

5.0
4.0


In [15]:
import numpy as np

a = np.array([[2, 1, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(np.linalg.det(a))
print(np.linalg.inv(a))

-9.000000000000002
[[ 0.33333333 -1.66666667  1.        ]
 [-0.66666667  0.33333333  0.        ]
 [ 0.33333333  1.         -0.66666667]]
